export const APP_WRITE_ID = 'crm-system-nuxt-lux1177'
export const DB_ID = 'crm-system-nuxt-api'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'